package com.alexbar.layoutbasic.movies_app.utils

object MovieConstants {
    const val see_all = "View All"
    const val movies = "MOVIES"
    const val series = "SERIES"
    const val summary = "Summary"
    const val see_more = "SEE MORE"
    const val see_less = "SEE LESS"
    const val base_url = "https://image.tmdb.org/t/p/w500/"
    const val movies_file = "movies.json"
    const val tv_series_file = "series.json"
    const val media_type_tv_series = "tv"
    const val media_type_movie = "movie"
    const val popularity = "Popularity"
    const val first_air_date = "First Air Date"
    const val release_date = "Release Date"
    const val action_delete_text = "Delete"
    const val media_type_tv_series_text = "TV SERIES"
    const val media_type_movie_text = "MOVIE"
    const val tab_trending = "Trending"
    const val tab_favorites = "Favorites"
    const val tab_mix = "Mix"
    const val api_base_url = "https://api.themoviedb.org/3/"
    const val user_token = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNjU3NzQ1MTgwMmM1MjI4OGEyY2Q2YTk4ODViNWMwOCIsInN1YiI6IjVlZTQ1NmNhOTdlYWI0MDAyMGU1ODhlNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Seh-Mv7MaNjhgZXSoLfFNvtJJwemtN5xf6xauqBu0CI"
}